services:
  - type: web
    name: my-nestjs-project
    env: node
    buildCommand: yarn install && yarn add -D @nestjs/cli && yarn build
    startCommand: yarn start:prod
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    plan: free